//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class MoveTo
{
	public double BackDistance { get; set; }
	public double RightDistance { get; set; }
	public double TurnCcwDeg { get; set; }
}
